### ISSUE TITLE
bad and good column names reversal?

### ISSUE THREAD

**Issue by scottlittle** [Densur/PyWoE#2]
After running mywoe.bins where mywoe = woe.WoE() and mywoe.fit(x,y), my counts for goods and bads are reversed.  My y variable denotes 1's as goods.  Isn't this normal?

**Comment by Densur** [comment]
Please provide more details or example.
As I currently understood it's normal:
The value of WoE will be 0 if the odds of Relative Frequency of Goods / Relative
Frequency Bads is equal to 1. **If the Relative Frequency of Bads in a group is greater
than the Relative Frequency of Goods, the odds ratio will be less than 1 and the WoE
will be a negative number;** if the Relative Frequency of Goods is greater than the Relative Frequency of Bads in a group, the WoE value will be a positive number.

For details see http://documentation.statsoft.com/portals/0/formula%20guide/Weight%20of%20Evidence%20Formula%20Guide.pdf
