### ISSUE TITLE
direction of WoE transformed variables is opposite to expected

### ISSUE THREAD

**Issue by dynamics77** [Densur/PyWoE#4]
Direction of WoE transformed variables with respect to the target variable appears to be opposite of expected as suggested by coefficients of a Linear model. Please see attached example code with this post. Working with PIMA Indians diabetes data predicting Diabetes outcome (https://archive.ics.uci.edu/ml/datasets/pima+indians+diabetes)  coefficient of "Age" variable is positive but WoE transformation is negatively related to Diabetes outcome. This is also true for other variables example Glucose.

<img width="679" alt="woeissue" src="https://user-images.githubusercontent.com/9534433/29971765-7fb6c706-8ef7-11e7-87d5-e57f75550744.png">

**Comment by Densur** [comment]
It's correct. WoE should be greater than zero in buckets with bad/good ratio lower than bad/good ratio in the sample. WoE of the bucket should be below zero if bad/good ratio is above than in the sample.
Please look at the example:
http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/
As the result, regression coefficients has inverse sign.

You can reverse bad and goods in your example to get coefficients of opposite sign.
